/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("io.github.niestrat99.java-conventions")
}

description = "AdvancedTeleport-Bukkit"
