###############################################################################
#                          -<( AdvancedTeleport )>-                           #
#                     Made by Niestrat99 and Thatsmusic99                     #
#                                                                             #
###############################################################################
# A rapidly growing teleportation plugin looking to break the boundaries of   #
# traditional teleport plugins.                                               #
#                                                                             #
# SpigotMC - https://www.spigotmc.org/resources/advanced-teleport.64139/      #
# Wiki - https://github.com/Niestrat99/AT-Rewritten/wiki                      #
# Discord - https://discord.gg/mgWbbN4                                        #
###############################################################################

# Another comment at the very top for all you lads :)

##############
#  Features  #
##############

# Whether basic teleportation features should be enabled or not.
# This includes /tpa, /tpahere, /tpblock, /tpunblock and /back.
# This does not disable the command for other plugins - if you want other plugins to use the provided commands, use Bukkit's commands.yml file.
# Please refer to https://bukkit.gamepedia.com/Commands.yml for this!
use-basic-teleport-features: true

# Whether warps should be enabled in the plugin.
use-warps: true

# Whether the plugin should modify spawn/spawn properties.
use-spawn: true

# Whether the plugin should allow random teleportation.
use-randomtp: true

# Whether homes should be enabled in the plugin.
use-homes: true

# The commands that AT should not register upon starting up.
# In other words, this gives up the command for other plugins to use.
# NOTE: If you are using Essentials with AT and want AT to give up its commands to Essentials, Essentials does NOT go down without a fight. Jesus Christ. You'll need to restart the server for anything to change.
disabled-commands: [ ]

#########################
#  Teleport Requesting  #
#########################

# How long tpa and tpahere requests last before expiring.
request-lifetime: 60

# Whether or not the plugin should enable the use of multiple requests.
# When enabled, user 1 may get TPA requests from user 2 and 3, but user 1 is prompted to select a specific request.
# When this is disabled and user 1 receives requests from user 2 and then 3, they will only have user 3's request to respond to.
allow-multiple-requests: true

# Let the player know when their request has timed out or been displaced by another user's request.
# Displacement only occurs when allow-multiple-requests is disabled.
notify-on-expire: true
tpa-restrict-movement-on: requester
tpahere-restrict-movement-on: requester

####################
#  Warm-Up Timers  #
####################

# The number of seconds it takes for the teleportation to take place following confirmation.
# (i.e. "You will teleport in 3 seconds!")
# This acts as the default option for the per-command warm-ups.
warm-up-timer-duration: 3

# Whether or not teleportation should be cancelled if the player rotates or moves.
cancel-warm-up-on-rotation: true

# Whether or not teleportation should be cancelled upon movement only.
cancel-warm-up-on-movement: true

# Command-specific warm-ups.
per-command-warm-ups:
  # Warm-up timer for /tpa.
  tpa: default
  # Warm-up timer for /tpahere
  tpahere: default
  # Warm-up timer for /tpr, or /rtp.
  tpr: default
  # Warm-up timer for /warp
  warp: default
  # Warm-up timer for /spawn
  spawn: default
  # Warm-up timer for /home
  home: default
  # Warm-up timer for /back
  back: default

###############
#  Cooldowns  #
###############

# How long before the user can use a command again.
# This stops users spamming commands repeatedly.
# This is also the default cooldown period for all commands.
cooldown-duration: 5

# Adds the warm-up duration to the cooldown duration.
# For example, if the cooldown duration was 5 seconds but the warm-up was 3, the cooldown becomes 8 seconds long.
add-cooldown-duration-to-warm-up: true

# Whether or not the cooldown of one command will stop a user from using all commands.
# For example, if a player used /tpa with a cooldown of 10 seconds but then used /tpahere with a cooldown of 5, the 10-second cooldown would still apply.
# On the other hand, if a player used /tpahere, the cooldown of 5 seconds would apply to /tpa and other commands.
apply-cooldown-to-all-commands: false

# When to apply the cooldown
# Options include:
# - request - Cooldown starts as soon as any teleport command is made and still applies even if no teleport takes place (i.e. cancelled by movement or not accepted).
# - accept - Cooldown starts only when the teleport request is accepted (with /tpyes) and still applies even if no teleport takes place (i.e. cancelled by movement).
# - teleport - Cooldown starts only when the teleport actually happens.
# Note:
# 'request' and 'accept' behave the same for /rtp, /back, /spawn, /warp, and /home
# cooldown for /tpall always starts when the command is ran, regardless if any player accepts or teleports
apply-cooldown-after: request

# Command-specific cooldowns.
per-command-cooldowns:
  # Cooldown for /tpa.
  tpa: default
  # Cooldown for /tpahere
  tpahere: default
  # Cooldown for /tpr, or /rtp.
  tpr: default
  # Cooldown for /warp
  warp: default
  # Cooldown for /spawn
  spawn: default
  # Cooldown for /home
  home: default
  # Cooldown for /back
  back: default

#########################
#  Teleportation Costs  #
#########################

# The amount it costs to teleport somewhere.
# If you want to use Vault Economy, use 100.0 to charge $100.
# If you want to use Minecraft EXP points, use 10EXP for 10 EXP Points.
# If you want to use Minecraft EXP levels, use 5LVL for 5 levels.
# If you want to use items, use the format MATERIAL:AMOUNT or MATERIAL:AMOUNT:BYTE.
# For example, on 1.13+, ORANGE_WOOL:3 for 3 orange wool, but on versions before 1.13, WOOL:1:3.
# If you're on a legacy version and unsure on what byte to use, see https://minecraftitemids.com/types
# To use multiple methods of charging, use a ; - e.g. '100.0;10LVL' for $100 and 10 EXP levels.
# To disable, just put an empty string, i.e. ''
cost-amount: 100.0

# Command-specific costs.
per-command-cost:
  # Cost for /tpa.
  tpa: default
  # Cost for /tpahere.
  tpahere: default
  # Cost for /tpr, or /rtp.
  tpr: default
  # Cost for /warp
  warp: default
  # Cost for /spawn
  spawn: default
  # Cost for /home
  home: default
  # Cost for /back
  back: default

#################
#  SQL Storage  #
#################

# Whether the plugin should use SQL storage or not.
# By default, AT uses SQLite storage, which stores data in a .db file locally.
use-mysql: false

# The MySQL host to connect to.
mysql-host: 127.0.0.1

# The port to connect to.
mysql-port: 3306

# The database to connect to.
mysql-database: database

# The username to use when connecting.
mysql-username: username

# The password to use when connecting.
mysql-password: password

# The prefix of all AT tables.
# If you're on Bungee, you may want to add your server's name to the end.
mysql-table-prefix: advancedtp

##########################
#  Distance Limitations  #
##########################

# Enables the distance limiter to stop players teleporting over a large distance.
# This is only applied when people are teleporting in the same world.
enable-distance-limitations: false

# The maximum distance that a player can teleport.
# This is the default distance applied to all commands when specified.
maximum-teleport-distance: 1000

# Whether or not all teleportations - not just AT's - should be checked for distance.
monitor-all-teleports-distance: false

# Determines the distance limit for each command.
per-command-distance-limitations:
  # Distance limit for /tpa
  tpa: default
  # Distance limit for /tpahere
  tpahere: default
  # Distance limit for /tpr
  tpr: default
  # Distance limit for /warp
  warp: default
  # Distance limit for /spawn
  spawn: default
  # Distance limit for /home
  home: default
  # Distance limit for /back
  back: default

###############################
#  Teleportation Limitations  #
###############################

# WARNING: A lot of the options below are considered advanced and use special syntax that is not often accepted in YAML.
# When using such options, wrap them in quotes: ''
# As an example, 'stop-teleportation-out:world,world_nether'

# Enables teleport limitations. This means cross-world or even world teleportation can be limited within specific worlds.
enable-teleport-limitations: false

# Whether or not all teleportation - not just AT's - should be checked to see if teleportation is allowed.
monitor-all-teleports-limitations: false

# The teleportation rules defined for each world.
# Rules include:
# - stop-teleportation-out - Stops players teleporting to another world when they are in this world.
# - stop-teleportation-within - Stops players teleporting within the world.
# - stop-teleportation-into - Stops players teleporting into this world.
# To combine multiple rules, use a ; - e.g. stop-teleportation-out;stop-teleportation-within
# For out and into rules, you can make it so that rules only initiate when in or going to a specific world using :, e.g. stop-teleportation-out:world stops players teleporting to "world" in the world they're currently in.
# To do the opposite (i.e. initiates the rule when users are not in the specified world), use !, e.g. stop-teleportation-into!world stops teleportation into a specific world if they are not in "world". If ! and : are used in the same rule, then : is given top priority.To make this rule work with multiple worlds, use a comma (,), e.g. stop-teleportation-into:world,world_nether
world-rules:
  default: stop-teleportation-within
  world: default
  # Stops people teleporting into the Nether if they're not coming from "world"
  world_nether: stop-teleportation-into!world

# The teleportation rules defined for each AT command.
# Rules include:
# - override - The command will override world rules and run regardless.
# - ignore - The command will refuse to run regardless of world rules.
# To combine multiple rules, use a ;.
# To make rules behave differently in different worlds, use : to initiate the rule in a specific world (e.g. override:world to make the command override "world"'s rules.)
# To initiate rules outside of a specific world, use ! (e.g. override!world to make the command override world rules everywhere but in world)
# To use multiple worlds, use a comma (,).
# By default, all commands will comply with the world rules. If no rules are specified, they will comply.
# All worlds specified will be considered the world in which the player is currently in. For worlds being teleported to, add > to the start of the world name.
# For example, ignore:world,>world_nether will not run if the player is in "world" or if the player is going into the Nether.
command-rules:
  tpa: ''
  tpahere: ''
  tpr: ''
  warp: ''
  spawn: ''
  home: ''
  back: ''

##############
#  RandomTP  #
##############

# Defines the range of X coordinates that players can teleport to.
# Using a value for example 5000 would automatically set the minimum to -5000.
# These are able to be defined for each world by name.
# Split the values with a semicolon (;).
# If a world is defined here but not in the z section, the x values will be reused for the z coords.
x:
  default: 5000;-5000
  world_the_end: 5000;-5000

# Defines the range of Z coordinates that players can teleport to.
# Using a value for example 5000 would automatically set the minimum to -5000.
# These are able to be defined for each world by name.
# Split the values with a semicolon (;).
# If a world is defined here but not in the z section, the x values will be reused for the z coords.
z:
  default: 5000;-5000
  world_the_end: 10000;-10000

# Deprecated
# The maximum X coordinate to go up to when selecting a random location.
maximum-x: 5000

# Deprecated
# The maximum Z coordinate to go up to when selecting a random location.
maximum-z: 5000

# The minimum X coordinate to go down to when selecting a random location.
minimum-x: -5000

# The minimum Z coordinate to go down to when selecting a random location.
minimum-z: -5000

# When WorldBorder is installed, AT will check the border of each world instead rather than using the minimum and maximum coordinates.
use-world-border: true

# If enabled checks if the player is in either an unclaimed area or that they have build permission in the area.
# Supported plugins are Lands, WorldGuard, and GriefPrevention.
protect-claim-locations: true

# Use the new rapid response system for RTP.
# This means valid locations are prepared before a user chooses to use /tpr or interact with a sign, meaning they are ready for use and can instantly TP a player.
# This feature allows you to use the "tpr" death option in the death management section further down.
# IMPORTANT NOTE - this feature only works on the Paper server type and any of its forks. It is not considered safe to use on Spigot or Bukkit.
use-rapid-response: true

# How many locations can be prepared per world when using AT's Rapid Response system.
# These are immediately prepared upon startup and when a world is loaded.
prepared-locations-limit: 3

# AT's Rapid Response system automatically loads locations for each world, but can be problematic on some worlds, mostly SkyBlock worlds.
# In response, this list acts as pro-active protection and ignores worlds generated using the following generators.
# This is provided as an option so you can have control over which worlds have locations load.
ignore-world-generators:
  - us.talabrek.ultimateskyblock.world.SkyBlockChunkGenerator
  - us.talabrek.ultimateskyblock.world.SkyBlockNetherChunkGenerator
  - world.bentobox.bskyblock.generators.ChunkGeneratorWorld
  - world.bentobox.acidisland.world.ChunkGeneratorWorld
  - world.bentobox.oneblock.generators.ChunkGeneratorWorld
  - com.wasteofplastic.askyblock.generators.ChunkGeneratorWorld
  - com.wasteofplastic.acidisland.generators.ChunkGeneratorWorld
  - b.a
  - com.chaseoes.voidworld.VoidWorld.VoidWorldGenerator
  - club.bastonbolado.voidgenerator.EmptyChunkGenerator

# Blocks that people must not be able to land in when using /tpr.
avoid-blocks:
  - WATER
  - LAVA
  - STATIONARY_WATER
  - STATIONARY_LAVA

# Biomes that the plugin should avoid when searching for a location.
avoid-biomes:
  - OCEAN
  - DEEP_OCEAN

# Whether or not /tpr should only be used in the worlds listed below.
whitelist-worlds: false

# Whether or not players should be directed to a whitelisted world when using /tpr.
# When this option is disabled and the player tries to use /tpr in a non-whitelisted world, the command simply won't work.
redirect-to-whitelisted-worlds: true

# Worlds you can use /tpr in.
# If a player uses /tpr in a world that doesn't allow it, they will be teleported in the first world on the list instead.
# To make this feature effective, turn on "whitelist-worlds" above.
allowed-worlds:
  - world
  - world_nether

###########
#  Homes  #
###########

# The default maximum of homes people can have.
# This can be overridden by giving people permissions such as at.member.homes.10.
# To disable this, use -1 as provided by default.
default-homes-limit: -1

# Whether or not the bed home should be added to /homes.
add-bed-to-homes: true

# Whether or not players should be denied access to some of their homes if they exceed their homes limit.
# The homes denied access to will end up being their most recently set homes.
# For example, having homes A, B, C, D and E with a limit of 3 will deny access to D and E.
deny-homes-if-over-limit: false

# If homes should be hidden from /homes should they be denied access.
# If this is false, they will be greyed out in the /homes list.
hide-homes-if-denied: false

##########################
#  Notifications/Sounds  #
##########################

# The sound played when a player receives a teleportation (tpa) request.
# For 1.16+, check https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html for a list of sounds you can use
# For 1.15 and below, check https://www.spigotmc.org/threads/sounds-spigot-1-7-1-14-4-sound-enums.340452/ for a list of sounds down to 1.7.
# (Friendly reminder that 1.7.x is not supported though!)
# Set to "none" if you want no sound playing.
tpa-request-received: none

# The sound played when a player sends a teleportation (tpa) request.
tpa-request-sent: none

# The sound played when a player receives a teleportation (tpahere) request.
tpahere-request-received: none

# The sound played when a player sends a teleportation (tpahere) request.
tpahere-request-sent: none

##########
#  Back  #
##########

# The teleport causes that the plugin must listen to allow players to teleport back to the previous location.
# You can see a full list of these causes at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/player/PlayerTeleportEvent.TeleportCause.html
used-teleport-causes:
  - COMMAND
  - PLUGIN
  - SPECTATE

# The cubic radius to search for a safe block when using /back.
# If a player teleports from an unsafe location and uses /back to return to it, the plugin will search all blocks within this radius to see if it is a safe place for the player to be moved to.
# It is recommend to avoid setting this option too high as this can have a worst case execution time of O(n^3) (e.g. run 27 times, 64, 125, 216 and so on).
# To disable, either set to 0 or -1.
back-search-radius: 5

######################
#  Spawn Management  #
######################

# Whether the player should be teleported to the spawnpoint when they join for the first time.
teleport-to-spawn-on-first-join: true

# Whether the player should be teleported to the spawnpoint every time they join.
teleport-to-spawn-on-every-join: false

# Determines how and where players teleport when they die.
# Options include:
# - spawn - Teleports the player to the spawnpoint of either the world or specified by the plugin.
# - bed - Teleports to the player's bed.
# - anchor - 1.16+ only, teleports to the player's respawn anchor. However, due to limitations with Spigot's API, it may or may not always work. (add Player#getRespawnAnchor pls)
# - warp:Warp Name - Teleports the player to a specified warp. For example, if you want to teleport to Hub, you'd type warp:Hub
# - tpr - Teleports the player to a random location. Can only be used when the rapid response system is enabled.- {default} - Uses the default respawn option, which is spawn unless set differently.
# If you're using EssentialsX Spawn and want AT to take over respawn mechanics, set respawn-listener-priority in EssX's config.yml file to lowest.
death-management:
  default: spawn
  world: 'default'
  special-world: warp:Special
  another-world: bed

#################
#  Permissions  #
#################

# The default permissions given to users without OP.
# By default, Advanced Teleport allows users without OP to use all member features.
# This allows for permission management without a permissions plugin, especially if a user doesn't understand how such plugins work.
# However, if you have a permissions plugin and Vault installed, you cannot make admin permissions work by default.
default-permissions:
  - at.member.*
  - at.member.warp.*

# Allows admin permissions to be allowed as default permissions by default.
# If you want to use admin permissions, it's often recommended to use a permissions plugin such as LuckPerms.
# Do not enable this if you are unsure of the risks this option proposes.
allow-admin-permissions-as-default-perms: false
