main: io.github.niestrat99.advancedteleport.CoreClass
name: AdvancedTeleport
version: 5.4.6-SNAPSHOT-1
description: A rapidly growing teleportation plugin looking to break the boundaries of traditional teleport plugins.
authors: [Niestrat99, Thatsmusic99]
contributors: [SuspiciousLookingOwl (Github), animeavi (Github), MrEngMan]
softdepend: [Vault, Ultimate_Economy, ConfigurationMaster]
loadbefore:
  - Essentials
api-version: 1.13

commands:
  warps:
    description: Gives you a list of warps.
    permission: at.member.warps
  warp:
    description: Teleports you to a specified warp.
    permission: at.member.warp
    usage: /warp <Warp name>
  setwarp:
    description: Sets a warp at your location.
    permission: at.admin.setwarp
    usage: /setwarp <Warp name>
  delwarp:
    description: Deletes a specified warp.
    permission: at.admin.delwarp
    usage: /delwarp <Warp name>
  movewarp:
    description: Moves a specified warp.
    permission: at.admin.movewarp
    usage: /movewarp <Warp name>
  tpr:
    description: Teleports you to a random place.
    permission: at.member.tpr
    aliases: rtp
    usage: /tpr [World]
  tpohere:
    description: (ADMIN ONLY COMMAND) Instantly teleports a player to you.
    permission: at.admin.tpohere
    usage: /tpohere <Player>
  tpaall:
    description: (ADMIN ONLY COMMAND) Sends a "TPAHere"-request to every online player.
    permission: at.admin.all
    aliases: tpall
  tpoff:
    description: Stops you from receiving teleport requests.
    permission: at.member.off
  tpon:
    description: Allows you to receive teleport requests.
    permission: at.member.on
  toggletp:
    description: Lets you switch between receiving tp requests and not receiving them.
    permission: at.member.toggletp
  tpcancel:
    description: Cancels a teleport request you've sent.
    permission: at.member.cancel
  tpunblock:
    description: Unblocks a player.
    permission: at.member.unblock
    usage: /tpunblock <Player>
  tpblock:
    description: Blocks and prevents a player to send a teleport request to you.
    permission: at.member.block
    usage: /tpblock <Player>
  tpdeny:
    description: Declines a teleport request someone sent you.
    permission: at.member.no
    aliases: [tpano , tpno]
  tpaccept:
    description: Accepts a teleport request someone sent you.
    permission: at.member.yes
    aliases: [tpayes , tpyes]
    usage: /tpaccept [Player]
  tpo:
    description: (ADMIN ONLY COMMAND) Instantly teleports you to another player.
    permission: at.admin.tpo
    usage: /tpo <Player>
  tpahere:
    description: Sends the targeted player a teleport requests to where you are.
    permission: at.member.here
    usage: /tpahere <Player>
  tpa:
    description: Sends the targeted player a teleport request to where they are.
    permission: at.member.tpa
    usage: /tpa <Player>
  athelp:
    description: Sends you a list of commands.
    permission: at.member.help
    usage: /athelp [Category]
  tpalist:
    description: Lists your teleport requests.
    permission: at.member.list
    usage: /tpalist
  spawn:
    description: Teleports you to the spawn location.
    permission: at.member.spawn
    usage: /spawn
  setspawn:
    description: Sets a spawn at your location.
    permission: at.admin.setspawn
    usage: /setspawn
  atreload:
    description: Reloads the Config.
    permission: at.admin.reload
    usage: /atreload
  sethome:
    description: Sets a home point at your location.
    permission: at.member.sethome
    usage: /sethome <Home>
  delhome:
    description: Deletes a home point you've set.
    permission: at.member.delhome
    usage: /delhome <Home>
  home:
    description: Sends you to your home point.
    permission: at.member.home
    usage: /home <Home>
  homes:
    description: Gives a list of homes you've set.
    permission: at.member.homes
    usage: /homes [Player]
  movehome:
    description: Moves a home to a new location.
    permission: at.member.movehome
    usage: /movehome <Home>
  setmainhome:
    description: Sets a user's main home.
    permission: at.member.setmainhome
    usage: /setmainhome <Home>
    aliases: [setmhome]
  back:
    description: Teleports you to your last location.
    permission: at.member.back
    usage: /back
  atinfo:
    description: Shows informations about this plugin.
    permission: at.admin.info
    usage: /atinfo
  tploc:
    description: Teleports you to a specified location.
    permission: at.admin.tploc
    usage: /tploc <x> <y> <z> [Yaw] [Pitch] [World] [Player]
  tpoffline:
    description: Teleports to an offline player.
    permission: at.admin.tpoffline
    usage: /tpoffline <Player>
    aliases: [tpoffl]
  tpofflinehere:
    description: Teleports an offline player to your location.
    permission: at.admin.tpofflinehere
    usage: /tpofflinehere <Player>
    aliases: [tpofflh, tpofflhere]
permissions:
  at.member.warp.*:
    default: op
  # Allows all member permissions
  at.member.*:
    default: op
    description: Allows access to member-based commands of the plugin.
    children:
      # All of these are "sub-permissions" of at.member.*.
      at.member.tpr: true
      at.member.off: true
      at.member.on: true
      at.member.toggletp: true
      at.member.cancel: true
      at.member.unblock: true
      at.member.block: true
      at.member.no: true
      at.member.yes: true
      at.member.here: true
      at.member.help: true
      at.member.list: true
      at.member.warp: true
      at.member.warps: true
      at.member.spawn: true
      at.member.sethome: true
      at.member.delhome: true
      at.member.home: true
      at.member.homes: true
      at.member.setmainhome: true
      at.member.tpa: true
      at.member.back: true
      at.member.spawn.use-sign: true
      at.member.randomtp.use-sign: true
      at.member.warp.use-sign: true
      at.member.warps.use-sign: true
      at.member.bed.use-sign: true
      at.member.back.death: true
      at.member.warps.location: true
      at.member.homes.location: true
  at.admin.*:
    default: op
    description: Allows access to admin-based commands of the plugin.
    children:
      at.admin.tpohere: true
      at.admin.all: true
      at.admin.tpo: true
      at.admin.help: true
      at.admin.rtpsign: true
      at.admin.setwarp: true
      at.admin.delwarp: true
      at.admin.warpsign: true
      at.admin.setspawn: true
      at.admin.spawnsign: true
      at.admin.reload: true
      at.admin.sethome: true
      at.admin.delhome: true
      at.admin.homes: true
      at.admin.home: true
      at.admin.info: true
      at.admin.bypass.distance-limit: true
      at.admin.sethome.bypass: true
      at.admin.toggletp: true
      at.admin.bypass: true
      at.admin.tploc: true
      at.admin.tploc.others: true
      at.admin.bypass.timer: true
      at.admin.bypass.cooldown: true
      at.admin.request-in-teleport: true
      at.admin.sign.spawn.create: true
      at.admin.sign.randomtp.create: true
      at.admin.sign.warp.create: true
      at.admin.sign.warps.create: true
      at.admin.sign.bed.create: true
      at.admin.tpoffline: true
      at.admin.tpofflinehere: true
      at.member.homes.unlimited: true