main: io.github.at.main.Main
name: AdvancedTeleport
version: 5.0.12
description: A plugin which is based on tons of teleport stuff.
authors: [Niestrat99,Thatsmusic99]
softdepend: [Vault, Ultimate_Economy]
api-version: 1.13


commands:

  warps:
    description: Gives you a list of warps.
    permission: at.member.warps
  warp:
    description: Gives you a list of sub commands from this command.
    permission: at.member.warp
  tpr:
    description: Teleports you to a random place.
    permission: at.member.tpr
    aliases: rtp
  tpohere:
    description: (ADMIN ONLY COMMAND) Instantly teleports a player to you.
    permission: at.admin.tpohere
  tpaall:
    description: (ADMIN ONLY COMMAND) Sends a "TPAHere"-request to every online player.
    permission: at.admin.all
    aliases: tpall
  tpoff:
    description: Stops you from receiving teleport requests.
    permission: at.member.off
  tpon:
    description: Allows you to receive teleport requests.
    permission: at.member.on
  toggletp:
    description: Lets you switch between receiving tp requests and not receiving them.
    permission: at.member.toggletp
  tpcancel:
    description: Cancels a teleport request you've sent.
    permission: at.member.cancel
  tpunblock:
    description: Unblocks a player.
    permission: at.member.unblock
  tpblock:
    description: Blocks and prevents a player to send a teleport request to you.
    permission: at.member.block
  tpdeny:
    description: Declines a teleport request someone sent you.
    permission: at.member.no
    aliases: [tpano , tpno]
  tpaccept:
    description: Accepts a teleport request someone sent you.
    permission: at.member.yes
    aliases: [tpayes , tpyes]
  tpo:
    description: (ADMIN ONLY COMMAND) Instantly teleports you to another player.
    permission: at.admin.tpo
  tpahere:
    description: Sends the targeted player a teleport requests to where you are.
    permission: at.member.here
  tpa:
    description: Sends the targeted player a teleport request to where they are.
    permission: at.member.tpa
  athelp:
    description: Sends you a list of commands.
    permission: at.member.help
  tpalist:
    description: Lists your teleport requests.
    permission: at.member.list
  spawn:
    description: Teleports you to the spawn location.
    permission: at.member.spawn
  setspawn:
    description: Sets a spawn at your location.
    permission: at.admin.setspawn
  atreload:
    description: Reloads the Config.
    permission: at.admin.reload
  sethome:
    description: Sets a home point at your location.
    permission: at.member.sethome
  delhome:
    description: Deletes a home point you've set.
    permission: at.member.delhome
  home:
    description: Sends you to your home point.
    permission: at.member.home
  homes:
    description: Gives a list of homes you've set.
    permission: at.member.homes
  back:
    description: Teleports you to your last location.
    permission: at.member.back
  atinfo:
    description: Shows informations about this plugin.
    permission: at.admin.info

permissions:
  at.member.warp.*:
    default: true
  # Allows all member permissions
  at.member.*:
    default: true
    description: Allows access to member-based commands of the plugin.
    children:
      # All of these are "sub-permissions" of tbh.tp.member.*.
      at.member.tpr: true
      at.member.off: true
      at.member.on: true
      at.member.toggletp: true
      at.member.cancel: true
      at.member.unblock: true
      at.member.block: true
      at.member.no: true
      at.member.yes: true
      at.member.here: true
      at.member.help: true
      at.member.list: true
      at.member.warp: true
      at.member.warps: true
      at.member.spawn: true
      at.member.sethome: true
      at.member.delhome: true
      at.member.home: true
      at.member.homes: true
      at.member.tpa: true
      at.member.back: true
      at.member.spawn.use-sign: true
      at.member.tpr.use-sign: true
      at.member.warp.use-sign: true
      at.member.back.death: true
  at.admin.*:
    default: op
    description: Allows access to admin-based commands of the plugin.
    children:
      at.admin.tpohere: true
      at.admin.all: true
      at.admin.tpo: true
      at.admin.help: true
      at.admin.rtpsign: true
      at.admin.warpset: true
      at.admin.warpdel: true
      at.admin.warpsign: true
      at.admin.setspawn: true
      at.admin.spawnsign: true
      at.admin.reload: true
      at.admin.sethome: true
      at.admin.delhome: true
      at.admin.homes: true
      at.admin.home: true
      at.admin.info: true
      at.admin.bypass.distance-limit: true
      at.admin.sethome.bypass: true
      at.admin.toggletp: true
      at.admin.bypass: true