# You may wish to alter this file to override the set of languages analyzed,
# or to provide custom queries or build logic.
#
# ******** NOTE ********
# We have attempted to detect the languages in your repository. Please check
# the `language` matrix defined below to confirm you have the correct set of
# supported CodeQL languages.
#
name: "Build Pull Request"

on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "v6" ]
  schedule:
    - cron: '38 18 * * 1'

jobs:
  check:
    name: Formatting Checks
    runs-on: ubuntu-latest
    if: false
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Tell Github Actions that Java 17 exists
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Check Google Java Format
        uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace --aosp"
          skip-commit: true

      - name: Print GVF diffs
        run: git --no-pager diff --exit-code

  autobuild:
    name: Autobuild
    runs-on: ubuntu-latest
    needs: check
    if: ${{ always() }}
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]
        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python', 'ruby' ]
        # Use only 'java' to analyze code written in Java, Kotlin or both
        # Use only 'javascript' to analyze code written in JavaScript, TypeScript or both
        # Learn more about CodeQL language support at https://aka.ms/codeql-docs/language-support

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Tell Github Actions that Java 17 exists
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
          # If you wish to specify custom queries, you can do so here or in a config file.
          # By default, queries listed here will override any specified in a config file.
          # Prefix the list here with "+" to use these queries and those in the config file.

          # Details on CodeQL's query packs refer to : https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#using-queries-in-ql-packs
          # queries: security-extended,security-and-quality


      # Autobuild attempts to build any compiled languages  (C/C++, C#, Go, or Java).
      # If this step fails, then you should remove it and run the build manually (see below)
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle
        run: ./gradlew slimJar

      - name: Force JSON files because life is tough and I am a programmer so naturally I work around everything that should be handled head-on
        run: zip -r -D -j build/advancedteleport-bukkit/libs/AdvancedTeleport-Bukkit-*-all.jar build/advancedteleport-bukkit/resources/slimjar/*.json

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:${{matrix.language}}"

      - name: Archive Artifact
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: AdvancedTeleport
          path: build/advancedteleport-bukkit/libs/AdvancedTeleport-Bukkit-*-all.jar
          if-no-files-found: error